# Pull the base image from tiangolo (since we are using FastAPI to write the API) from Docker Hub
FROM tiangolo/uvicorn-gunicorn-fastapi:python3.10

# Upgrade pip and install requirements.
COPY ./requirements.txt /server/requirements.txt
# COPY ./requirements.txt /server/requirements.txt
RUN pip install --upgrade pip
RUN pip install -r /server/requirements.txt

# Clean the install
RUN apt-get -y clean

# Copy all files to /app directory and move into directory.
COPY ./ /server
# COPY ./ /server

# Change the working directory to /authentication_service/app
WORKDIR /server

# Run the fast application
CMD ["python", "main.py"]