FROM python:3.10-slim-buster

# Upgrade pip and install requirements.
COPY ./queue_consumer_template/requirements.txt /server/requirements.txt
RUN pip install --upgrade pip
RUN pip install -r /server/requirements.txt

# Clean the install
# 
RUN apt-get -y clean

# Copy all files to /app directory and move into directory.
COPY ./queue_consumer_template/app /server/app/

# Change the working directory to /authentication_service/app
WORKDIR /server/app

# Run the fast application
CMD ["python", "main.py"]