version: "3.9"

services:
  queue_service:
    image: rabbitmq:3.11-management-alpine
    # How do you pass arguments to the docker image?

    environment:
      - RABBITMQ_DEFAULT_USER=user
      - RABBITMQ_DEFAULT_PASS=password
    container_name: 'queue_service'
    # Exposes two ports, one is the default porer for rabbitmq, the other is the management port
    ports:
        - 5672:5672
        - 15672:15672
 
  
  queue_consumer_template:
    build:
      context: ./
      dockerfile: ./Dockerfile.dev
    container_name: queue-consumer
    tty: true
    restart: "always"
    volumes:
      - ./:/server
    depends_on:
      - queue_service



